### ISSUE TITLE
[Kotlin SDK] Regex in extensions.kt for isFioAddress is incorrect

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fiosdk_kotlin#10]
In extensions.kt the regex for isFioAddress is incorrect. According to:
https://developers.fioprotocol.io/api/api-spec/reference/register-fio-address/register-fio-address-model
the regex should be:
^(?:(?=.{3,64}$)[a-zA-Z0-9]{1}(?:(?!-{2,}))[a-zA-Z0-9-](?:(?<!-))@[a-zA-Z0-9]{1}(?:(?!-{2,}))[a-zA-Z0-9-](?:(?<!-))$)
(dev should confirm this)

All of the regex strings in extensions.kt should be confirmed.

**Comment by ericbutz** [comment]
Shawn Mullen May 2nd  1:57 AM
I saw the messages regarding the regex for FIO Address validation in the kotlin SDK.  I don’t know how the backslash got added.  I know I didn’t type out the regex.  I copied it from somewhere.  I don’t remember where.  However, I took a look at the other regexes in the kotlin sdk, in the Extension.kt file.  The other regexes have the same issue!
I wanted to make sure you knew.  Those regex need the backslash removed as well.

**Comment by blockpane** [comment]
I'll throw in my 2 cents ... that regex (which is my fault) was thrown together as more of a curiosity, just to see *if* it could be done as a one-liner. But, since it's using both look-aheads and look-behinds it is incredibly expensive.  I didn't even use it in the go library (partly because the Go core devs refuse to implement la/lb in the regex library, and because it's slow.) https://github.com/fioprotocol/fio-go/blob/develop/address.go#L29

**Comment by ericbutz** [comment]
Todd has a good point, we may want to simplify the domain and address checks.

**Comment by ericbutz** [comment]
Completed. Will be released with SDK 1.1.x.
