### ISSUE TITLE
[Kotlin SDK] Add removePublicAddresses to SDK

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fiosdk_kotlin#6]
Add the new reomovePublicAddress call to the Kotlin SDK.

**Comment by edrotthoff** [comment]
updates have been made and placed into a PR into master, this will be given a very detailed review by Shawn Mullen and all comments will be addressed...after all conversations on the PR are closed the PR can then be merged.

https://github.com/fioprotocol/fiosdk_kotlin/pull/11

**Comment by edrotthoff** [comment]
the development unit tests need to be modified to match the testnet unit tests, this will be completed ASAP and added into the PR.

**Comment by edrotthoff** [comment]
all comments were addressed, an upgrade to the android studio, Kotlin and Gradle (since the time of Shawns layoff) caused some issues, but was resolved when I found the necessary changes required of the Gradle build file, Shawn and I are now on the same versions of android studio and Gradle, documentation generates successfully for both of us, and we did a final review of the generated documentation and this was added into the PR...this PR is now in final form and may be merged.
https://github.com/fioprotocol/fiosdk_kotlin/pull/11

**Comment by ericbutz** [comment]
Let's revert and merge into develop

**Comment by ericbutz** [comment]
Tracked in Atlassian. Closing.
